[package]
org = "ballerinax"
name = "cdc"
version = "@toml.version@"
distribution = "2201.12.0"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-cdc"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib.cdc"
artifactId = "cdc-native-@project.version@"
version = "@project.version@"
path = "../native/build/libs/cdc-native-@project.version@.jar"
