[package]
org = "ballerinax"
name = "cdc"
version = "0.1.0"
distribution = "2201.12.0"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-cdc"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib.cdc"
artifactId = "cdc-native-0.1.0-SNAPSHOT"
version = "0.1.0-SNAPSHOT"
path = "../native/build/libs/cdc-native-0.1.0-SNAPSHOT.jar"
